### ISSUE TITLE
Can't work with python2.7

### ISSUE THREAD

**Issue by Loganli0881** [MichaelAquilina/flake8-spellcheck#15]
My Python version is 2.7, flake8 version is 3.5.0 (flake8-future-import: 0.4.5, mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.17 on Darwin
after i install flake8-spellcheck-0.9.1, it can't work anymore.

`(mywork) loganlideMacBook-Pro:test $ flake8 test.py
Traceback (most recent call last):
  File "/Users/timeless/.vitualenvs/mywork/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/Users/timeless/.vitualenvs/mywork/lib/python2.7/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "SC" due to invalid syntax (__init__.py, line 153).`

Can you help me solve this problem? 
Thank you!

**Comment by MichaelAquilina** [comment]
This project is python 3.5+ only

There seems to be a wrongly specified python2 support in the `setup.py` file which I will fix. 

Python 2.7 is about to me marked as end of life (1st January 2020) so I really recommend you update your projects to python3 as soon as possible!
